---
title: "Mesures physiologiques de joueurs de jeu vidéo (2)"
subtitle: "Analyse par expériences"
author: "Godefroy Clair"
date: "15 janvier 2016"
output:
  html_document:    
    number_sections: yes
    toc: yes
  word_document: default
---


```{r, echo=FALSE, cache= FALSE ,comment='', warning=F,message=F}
##Laisser le cache à False, sinon les bibliothèques ne sont pas chargées...
require(knitr)
require(plyr)
require(ggplot2)
require(reshape2)
require(scatterplot3d)
require(grDevices)
require(kohonen)
require(ggdendro)
require(grid)
require(zoo)
```


```{r, echo = F, cache=T}

mac.gd.path <- "/Users/godot/githubRepos/"
hp.gd.path <- "C:/Users/Godefroy/githubRepos/"


if(Sys.info()['nodename']=="THIM")gd.path <- hp.gd.path else
  gd.path <- mac.gd.path
data.path <- paste(gd.path,"affectiveComputing/data",sep = "/")
```

```{r, echo = F, cache=T}

rda.save <- paste(data.path ,"data-frame-all-expe.Rda",sep = "/")
load(rda.save)
#enregistrement des données
hcluster.save <- paste(data.path ,"hClustering.Rda",sep = "/")
load(hcluster.save)
#enregistrement des données
som1.save <- paste(data.path ,"som1.Rda",sep = "/")
load(som1.save)

```

\newpage

#Introduction

Bla bla bla

Listes des expériences 
```{r, echo=F, cache=T}
df.selec <- df.all[!(df.all$nom.experience %in% c("FS1","LM","HL","ST")),]
list.expe.selec <- c("AB", "CLP", "CW", "DA", "PCo", "PCo2", "PCo3","DE")
df.selec$tps.ecoule <- as.numeric(df.selec$date)
df.selec$tps.ecoule.norm <- df.selec$tps.ecoule
df.selec$nom.neurone <- som1$unit.classif
```


```{r, echo=F, cache=T}
#Utilis par la suite...

# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2,   byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)
  
  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }
 
 if (numPlots==1) {
    print(plots[[1]])
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
       
    # Make each plot, in the correct location
    for (i in 1:(numPlots)) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
     
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
      
    }
  }
}

```

#Experience PCo

\newgeometry{left=0.5cm, right=0.5cm,bottom=3cm,top=0cm}

```{r, echo=F, cache=T, fig.height=18, fig.width=18, fig.cap="déplacement des données entre les neurones par expérience"}

list.gg <- lapply(list.expe.selec, function(nom.expe) { 
  g<- ggplot(data = df.selec[df.selec$nom.experience==nom.expe,], aes (tps.ecoule.norm,nom.neurone)) + 
    geom_line(aes(colour = tps.ecoule.norm)) + 
    scale_color_continuous(name="temps écoulé)", low = "yellow",high = "red") + 
    xlab("proportion du temps écoulé") + 
    ylab("numéro du neurone") + ggtitle(paste("déplacement des données de",nom.expe,"entre les neurones",sep = " "))+ 
    scale_y_continuous(breaks=seq(0,900,by = 10)) +
    theme(axis.text.y=element_text(colour = 'black', size = 7)) 
  })

multiplot(list.gg[[1]],list.gg[[2]],list.gg[[3]],list.gg[[4]],list.gg[[5]],list.gg[[6]],list.gg[[7]],list.gg[[8]],cols = 2)

#do.call("multiplot", as.list(list.gg,cols=2)) 

```
\restoregeometry
